### ISSUE TITLE
Release notes exceeds maximum character limit

### ISSUE THREAD

**Issue by josinaldobarbosa** [guness/bitrise-step-firebase-app-distribution#41]
`Error: failed to update release notes with HTTP Error: 400, Release notes length exceeds maximum character limit`

I think my release notes are 71696 characters.
I saw on the console that the maximum accepted is 16384 characters (manually found out), I didn't find any limit value in the doc for cli.

**Comment by guness** [comment]
can you please report this to firebase developers? we can't control limits on this step.

**Comment by josinaldobarbosa** [comment]
It doesn't make sense to me, if there is a limit we must respect, I created a mr that at least prevents the step from breaking the build

**Comment by guness** [comment]
I am sorry for the effort you put in but I have to disagree. As an end-user, I would piss off if a step decides to truncate my input.

Besides, this step is not managing the limit. So can you think of what happens when firebase decides to increase or decrease this limit? The step will be either truncating for nothing, or it will false promise safety.

**Comment by josinaldobarbosa** [comment]
understand, thank you for the answer
